### ISSUE TITLE
Fix crash in `create_run` function of `dialogue.py`

### ISSUE THREAD

**Issue by mbottini** [PDXCapstoneF/SPECtate#171]
```
-> create run
Input the run type. Current options: HBIR HBIR_RT
-> stuff
stuff is not currently an option. Add it? no
Traceback (most recent call last):
  File "mainCLI.py", line 171, in <module>
    r = func(arguments)
  File "mainCLI.py", line 134, in do_dialogue
    dialogue.dialogue()
  File "/home/mike/SPECtate/dialogue.py", line 461, in dialogue
    run_list, template_dict = function_dict.get(user_input, error)(run_list, template_dict)
TypeError: 'NoneType' object is not iterable
```

I'm not returning `run_list, runtype_config`.

**Comment by mbottini** [comment]
Fixed with Pull Request #173.
