### ISSUE TITLE
Fix second bug in create_run

### ISSUE THREAD

**Issue by mbottini** [PDXCapstoneF/SPECtate#174]
```
-> create run
Input the run type. Current options: HBIR HBIR_RT
-> HBIR
Input a tag for the run. TAG
Tag TAG already exists in the run list!
Input a tag for the run. specjbb
Tag specjbb already exists in the run list!
Input a tag for the run. new_tag
Kit Version: blah
JDK: 192
RTSTART: 4
JVM Options: aklsdnao
NUMA Nodes: 4
Data Collection: NONE
T1: 4
T2: 12
T3: 4
Add run new_tag to list? yes
Run new_tag added to list.
Traceback (most recent call last):
  File "mainCLI.py", line 171, in <module>
    r = func(arguments)
  File "mainCLI.py", line 134, in do_dialogue
    dialogue.dialogue()
  File "/home/mike/SPECtate/dialogue.py", line 461, in dialogue
    run_list, template_dict = function_dict.get(user_input, error)(run_list, template_dict)
  File "/home/mike/SPECtate/dialogue.py", line 127, in create_run
    return run_list, runtype_dict
NameError: name 'runtype_dict' is not defined

```

**Comment by mbottini** [comment]
Closed with Pull Request #175.
